# Generated by Django 2.0.2 on 2018-04-22 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2018, 4, 22, 12, 20, 24, 517606, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='images')),
                ('date', models.DateField(default=datetime.datetime(2018, 4, 22, 12, 20, 24, 520011, tzinfo=utc))),
                ('category', models.ManyToManyField(to='course.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='images')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('date', models.DateField(default=datetime.datetime(2018, 4, 22, 12, 20, 24, 518080, tzinfo=utc))),
                ('category', models.ManyToManyField(to='course.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2018, 4, 22, 12, 20, 24, 517002, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ManyToManyField(to='course.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='course.Lesson'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(to='course.Subject'),
        ),
    ]
