# Generated by Django 2.0.2 on 2018-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180224_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
