# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2017, 8, 8, 21, 5, 2, 488327, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Screencast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='videos')),
                ('date', models.DateField(default=datetime.datetime(2017, 8, 8, 21, 5, 2, 493436, tzinfo=utc))),
                ('categories', models.ManyToManyField(to='screencast.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2017, 8, 8, 21, 5, 2, 484292, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='screencast',
            name='subjects',
            field=models.ManyToManyField(to='screencast.Subject'),
        ),
    ]
